server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - JwtAuthentication
            - RewritePath=/auth(?<segment>/?.*), $\{segment}
        - id: transaction_service
          uri: http://localhost:8082
          predicates:
            - Path=/transaction/**
          filters:
            - JwtAuthentication
            - RewritePath=/transaction(?<segment>/?.*), $\{segment}
