server:
  port: 8080
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${PET_DATABASE_HOST}:${PET_DATABASE_PORT}/${PET_DATABASE_NAME}
    username: ${PET_DATABASE_USER}
    password: ${PET_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
